id: tenzir-ship
name: Tenzir Ship
description: >-
  Ship faster with automated release engineering. Manage changelogs, generate
  release notes, publish GitHub releases.
repository: tenzir/ship
components:
  cli: The command-line interface of `tenzir-ship`.
  python: User-facing Python API.
